export const links = [
	{
		name: "Home",
		hash: "#home",
	},
  {
    name: "Skills",
    hash: "#skills",
  },
  {
    name: "About",
    hash: "#about",
  },
	{
		name: "Projects",
		hash: "#projects",
	},
	{
		name: "Blogs",
		hash: "#blogs",
	},
	{
		name: "Contact",
		hash: "#contact",
	},
] as const;

export const skills = [
	"HTML",
	"CSS",
	"JavaScript",
	"TypeScript",
	"React",
	"Redux",
	"Node.js",
	"Express.js",
	"MongoDB",
	"Next.js",
	"Prisma",
	"Tailwind CSS",
	"Material UI",
	"Styled Components",
	"Git",
] as const;

export const projects = [
  {
    title: "portfolio",
    img: "/projects/portfolio.png",
    des: "My personal portfolio website built with Next.js and TypeScript. It showcases my projects, blogs, skills, and experiences.",
    stack: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "React Icons",
      "Context API",
      
    ],
    live: "https://suryakant-kumar.vercel.app/",
    github: "https://github.com/IM-Suryakant-Kumar/suryakantkumar.com",
  },
	{
		title: "ClenchSnap",
		img: "/projects/snap.png",
		des: "A Social media app",
		stack: [
			"ReactJS",
			"TypeScript",
			"React Router v6",
			"Context API with useReducer",
			"React Router data APIs",
			"React Toastify",
			"TailwindCSS",
			"NodeJS",
			"ExpressJS",
			"MongoDB",
			"Cloudinary",
			"JWT",
			"BcryptJS",
		],
		live: "https://clench-snap.vercel.app/",
		github: "https://github.com/IM-Suryakant-Kumar/ClenchSnap",
	},
	{
		title: "ClenchCart",
		img: "/projects/cart.png",
		des: "An E-commerce App",
		stack: [
			"ReactJS",
			"Redux Toolkit",
			"React Router v6",
			"React Router data APIs",
			"React Toastify",
			"MaterialUI",
			"Styled-Components",
			"NodeJS",
			"ExpressJS",
			"MongoDB",
			"Cloudinary",
			"JWT",
			"BcryptJS",
		],
		live: "https://clench-cart.vercel.app/",
		github: "https://github.com/IM-Suryakant-Kumar/clench-cart",
	},
	{
		title: "ClenchMedia",
		img: "/projects/media.png",
		des: "A video library App",
		stack: [
			"ReactJS",
			"TypeScript",
			"React Router v6",
			"React Router data APIs",
			"React Toastify",
			"Styled-Components",
			"NodeJS",
			"ExpressJS",
			"MongoDB",
			"Cloudinary",
			"JWT",
			"BcryptJS",
		],
		live: "https://clench-media.vercel.app/",
		github: "https://github.com/IM-Suryakant-Kumar/ClenchMedia",
	},
	{
		title: "ClenchKeep",
		img: "/projects/keep.png",
		des: "A note App",
		stack: [
			"TypeScript",
			"ReactJS",
			"React Router v6",
			"Redux Toolkit",
			"RTK Query",
			"React Toastify",
			"CSS Modules",
			"NodeJS",
			"ExpressJS",
			"MongoDB",
			"JWT",
			"BcryptJS",
		],
		live: "https://clench-keep.vercel.app/",
		github: "https://github.com/IM-Suryakant-Kumar/ClenchKeep",
	},
	{
		title: "ClenchUI",
		img: "/projects/ui.png",
		des: "A component library to make your next fastly and easily",
		stack: ["HTML", "CSS", "JavaScript"],
		live: "https://clenchui.netlify.app/",
		github: "https://github.com/IM-Suryakant-Kumar/ClenchUI",
	},
	{
		title: "ClenchMTS",
		img: "/projects/mts.png",
		des: "A Mern Stack starter template",
		stack: [
			"TypeScript",
			"ReactJS",
			"React Router v6",
			"React Toastify",
			"TailwindCSS",
			"NodeJS",
			"ExpressJS",
		],
		live: "https://clenchmts.vercel.app/",
		github: "https://github.com/IM-Suryakant-Kumar/ClenchMTS",
	},
] as const;

export const blogs = [
	{
		title: "WebScrapping Guide",
		desc: "coming soon...",
		link: "coming soon!",
	},
	{
		title: "Promises to Async Await",
		desc: "coming soon...",
		link: "coming soon!",
	},
	{
		title: "Automation Guide",
		desc: "coming soon...",
		link: "coming soon!",
	},
] as const;
