export const links = [
	{
		name: "Home",
		href: "#home",
	},
	{
		name: "About",
		href: "#about",
	},
	{
		name: "Skills",
		href: "#skills",
	},
	{
		name: "Projects",
		href: "#projects",
	},
	{
		name: "Blogs",
		href: "#blogs",
	},
	{
		name: "Contact",
		href: "#contact",
	},
];

export const skills = [
	"HTML",
	"CSS",
	"JavaScript",
	"TypeScript",
	"React",
	"React Router",
	"Context API",
	"Redux Toolkit",
	"Node.js",
	"Express.js",
	"MongoDB",
	"Git",
	"Tailwind CSS",
	"Bootstrap",
	"Material UI",
	"Styled Components",
	"JWT",
	"REST APIs",
];

export const projects = [
	{
		title: "ClenchSnap",
		img: "/projects/snap.png",
		des: "A Social media app",
		stack: [
			"ReactJS",
			"TypeScript",
			"React Router",
			"Context API",
			"TailwindCSS",
			"NodeJS",
			"ExpressJS",
			"MongoDB",
			"Cloudinary",
			"JWT",
			"BcryptJS",
		],
		live: "https://clench-snap.vercel.app/",
		github: "https://github.com/IM-Suryakant-Kumar/ClenchSnap",
	},
	{
		title: "ClenchCart",
		img: "/projects/cart.png",
		des: "An E-commerce App",
		stack: [
			"ReactJS",
			"Redux Toolkit",
			"React Router",
			"MaterialUI",
			"Styled-Components",
			"NodeJS",
			"ExpressJS",
			"MongoDB",
			"Cloudinary",
			"JWT",
			"BcryptJS",
		],
		live: "https://clench-cart.vercel.app/",
		github: "https://github.com/IM-Suryakant-Kumar/clench-cart",
	},
	{
		title: "ClenchMedia",
		img: "/projects/media.png",
		des: "A video library App",
		stack: [
			"ReactJS",
			"TypeScript",
			"React Router",
			"Styled-Components",
			"NodeJS",
			"ExpressJS",
			"MongoDB",
			"Cloudinary",
			"JWT",
			"BcryptJS",
		],
		live: "https://clench-media.vercel.app/",
		github: "https://github.com/IM-Suryakant-Kumar/ClenchMedia",
	},
	{
		title: "ClenchKeep",
		img: "/projects/keep.png",
		des: "A note App",
		stack: [
			"TypeScript",
			"ReactJS",
			"React Router",
			"Redux Toolkit",
			"RTK Query",
			"CSS Modules",
			"NodeJS",
			"ExpressJS",
			"MongoDB",
			"JWT",
			"BcryptJS",
		],
		live: "https://clench-keep.vercel.app/",
		github: "https://github.com/IM-Suryakant-Kumar/ClenchKeep",
	},
	{
		title: "ClenchUI",
		img: "/projects/ui.png",
		des: "A component library to make your next fastly and easily",
		stack: ["HTML", "CSS", "JavaScript"],
		live: "https://clenchui.netlify.app/",
		github: "https://github.com/IM-Suryakant-Kumar/ClenchUI",
	},
	{
		title: "ClenchMTS",
		img: "/projects/mts.png",
		des: "A Mern Stack starter template",
		stack: [
			"TypeScript",
			"ReactJS",
			"React Router",
			"TailwindCSS",
			"NodeJS",
			"ExpressJS",
		],
		live: "https://clenchmts.vercel.app/",
		github: "https://github.com/IM-Suryakant-Kumar/ClenchMTS",
	},
];

export const blogs = [
	{
		title: "WebScrapping Guide",
		des: "coming soon...",
		link: "coming soon!",
	},
	{
		title: "Promises to Async Await",
		des: "coming soon...",
		link: "coming soon!",
	},
	{
		title: "Automation Guide",
		des: "coming soon...",
		link: "coming soon!",
	},
];